// 개념집: 함수·문법 사전 + 문제별 해설
// 목표: 답안지를 이해하고 외운 뒤, 안 보고 재현하는 학습 흐름을 앱 안에서 끝내기
"use strict";

/* ── 함수·문법 사전 ─────────────────────────────────
   각 항목: name(이름) / sig(생김새) / what(들어가는 것 → 나오는 것) /
   when(언제 쓰나) / ex(미니 예제) */
const FUNC_DICT = {
  // ── 입력 ──
  input_readline: {
    name: "sys.stdin.readline",
    sig: "import sys → input = sys.stdin.readline",
    what: "표준입력에서 한 줄을 문자열로 읽어온다. 끝에 개행문자(\\n)가 붙어 있음. int()나 split()이 개행을 알아서 무시해줘서 보통 그대로 써도 된다.",
    when: "기본 input()은 한 줄에 마이크로초 단위로 느려서, 입력이 수만 줄이면 시간 초과가 난다. 코테에서는 거의 반사적으로 맨 위에 붙이는 관용구.",
    ex: "input = sys.stdin.readline\nn = int(input())  # '5\\n' → 5",
  },
  read_split: {
    name: "sys.stdin.read().split()",
    sig: "data = sys.stdin.read().split()",
    what: "입력 전체를 한 번에 읽어서(read) 공백·개행 기준으로 쪼갠(split) 문자열 리스트를 만든다. 줄 구분이 사라지고 토큰만 남는다.",
    when: "입력이 아주 많고, 줄 단위 구조가 중요하지 않을 때 가장 빠른 방법. data[0], data[1]처럼 인덱스로 꺼내 쓴다.",
    ex: "data = sys.stdin.read().split()\n# 입력 '3\\na b\\nc' → ['3','a','b','c']",
  },
  buffer_read: {
    name: "sys.stdin.buffer.read()",
    sig: "data = sys.stdin.buffer.read().split()",
    what: "read()의 바이트(bytes) 버전. 문자열 변환을 건너뛰어서 조금 더 빠르다. split() 결과도 바이트 조각이라 숫자로 쓰려면 int()로 변환한다(int는 바이트도 받아준다).",
    when: "입력이 수십만 토큰 이상이고 1초가 아까울 때. 동작은 read().split()과 같다고 생각하면 된다.",
    ex: "data = sys.stdin.buffer.read().split()\nn = int(data[0])",
  },
  split: {
    name: "문자열.split()",
    sig: "s.split()  또는  s.split(구분자)",
    what: "문자열이 들어가고 → 조각들의 리스트가 나온다. 인자를 안 주면 공백·탭·개행을 전부 구분자로 쓰고 빈 조각은 버린다.",
    when: "'kim 90' 같은 한 줄을 ['kim', '90']으로 쪼갤 때. 코테 입력 파싱의 기본.",
    ex: "'4 2'.split()  # → ['4', '2']",
  },
  map_int: {
    name: "map(int, ...)",
    sig: "map(함수, 반복가능한것)",
    what: "리스트(등)의 각 원소에 함수를 하나씩 적용한 결과를 내놓는다. map(int, ['4','2'])는 4와 2를 차례로 내놓는 '지연 계산' 객체 — list()로 감싸면 리스트가 되고, 변수 두 개에 바로 풀 수도 있다.",
    when: "입력 줄의 문자열 조각들을 한 방에 전부 숫자로 바꿀 때. n, k = map(int, input().split())은 코테 1번 관용구.",
    ex: "n, k = map(int, '4 2'.split())  # n=4, k=2\narr = list(map(int, input().split()))",
  },
  int_fn: {
    name: "int()",
    sig: "int(문자열 또는 숫자)",
    what: "문자열 '42'가 들어가면 정수 42가 나온다. 문자열 앞뒤 공백·개행은 무시해준다.",
    when: "입력은 전부 문자열로 들어오므로, 계산할 값은 반드시 int()로 바꿔야 한다. '9' < '10'이 False가 되는 문자열 비교 사고를 막는 것.",
    ex: "int('42\\n')  # → 42",
  },
  list_fn: {
    name: "리스트 기본기",
    sig: "lst = [] / lst.append(x) / lst[i] / len(lst)",
    what: "순서 있는 값들의 모음. append(x)는 맨 뒤에 추가(빠름), lst[i]는 i번째 접근(0부터 시작), len은 개수.",
    when: "거의 모든 문제. '입력을 리스트에 모은다 → 정렬하거나 훑는다'가 코테의 뼈대다.",
    ex: "rows = []\nrows.append((90, 'kim'))",
  },
  sort_key: {
    name: "sort와 key",
    sig: "lst.sort()  /  lst.sort(key=lambda x: ...)",
    what: "리스트를 제자리에서 오름차순 정렬한다. key에 함수를 주면 '각 원소를 무엇으로 바꿔서 비교할지'를 정한다. key가 튜플을 돌려주면 첫 값으로 먼저, 같으면 둘째 값으로 비교(다중 기준 정렬).",
    when: "정렬 문제의 90%. '점수 내림차순, 같으면 이름 오름차순' 같은 요구는 key=lambda x: (-점수, 이름) 한 줄로 끝난다.",
    ex: "iv.sort(key=lambda x: (x[1], x[0]))  # 끝시간→시작시간 순",
  },
  neg_trick: {
    name: "음수 트릭 (내림차순+오름차순 섞기)",
    sig: "(-점수, 이름) 튜플로 저장 후 그냥 sort()",
    what: "숫자에 -를 붙여 저장하면 오름차순 정렬이 곧 원래 값의 내림차순이 된다. 문자열은 -를 못 붙이므로, '숫자는 내림차순 + 문자열은 오름차순'을 동시에 하려면 숫자 쪽에만 -를 붙인다.",
    when: "정렬 기준이 방향이 서로 다른 혼합일 때. reverse=True는 전부 뒤집어버려서 이 경우 못 쓴다.",
    ex: "rows.append((-int(score), name)); rows.sort()",
  },
  tuple_compare: {
    name: "튜플 비교 규칙",
    sig: "(a1, b1) < (a2, b2)",
    what: "튜플끼리 비교하면 첫 원소부터 차례로 비교하고, 같으면 다음 원소로 넘어간다. 정렬·min·max가 전부 이 규칙을 따른다.",
    when: "다중 기준 정렬/최솟값의 원리. '이 튜플을 정렬하면 어떤 순서가 되나'를 읽을 수 있어야 답안이 읽힌다.",
    ex: "(-3, 'kim') < (-3, 'lee')  # True (숫자 같아서 문자열 비교)",
  },
  join: {
    name: "'구분자'.join()",
    sig: "'\\n'.join(문자열들)",
    what: "문자열 리스트가 들어가고 → 구분자로 이어 붙인 문자열 하나가 나온다. 원소가 숫자면 str()로 먼저 바꿔야 한다.",
    when: "결과 N줄을 print 한 번으로 출력할 때. print를 수만 번 부르면 느려서, 모아서 join으로 한 번에 뽑는 게 관용구.",
    ex: "print('\\n'.join(['a','b']))  # a\\nb",
  },
  slice: {
    name: "슬라이싱",
    sig: "lst[시작:끝]  (끝 미포함)",
    what: "리스트의 일부를 새 리스트로 잘라낸다. lst[:k]는 앞에서 k개, lst[1:]는 첫 원소 빼고 전부.",
    when: "정렬 후 상위 K개 뽑기, 입력 토큰에서 필요한 구간만 취하기.",
    ex: "rows[:k]  # 상위 k개",
  },
  counter: {
    name: "collections.Counter",
    sig: "from collections import Counter → c = Counter(리스트)",
    what: "리스트가 들어가면 {원소: 등장횟수} 딕셔너리가 나온다. c.items()는 (원소, 횟수) 쌍들.",
    when: "'가장 많이 나온 것', '종류별 개수' — 세는 문제는 일단 Counter. 직접 딕셔너리로 세는 것보다 짧고 빠르다.",
    ex: "Counter(['a','b','a'])  # {'a':2, 'b':1}",
  },
  min_max_key: {
    name: "min / max와 key",
    sig: "min(반복가능, key=lambda x: ...)",
    what: "여러 값 중 최솟값(최댓값)을 돌려준다. key를 주면 '무엇을 기준으로 비교할지'를 바꾼다. 정렬 안 하고 1등만 뽑을 때 정렬(N log N)보다 빠르다(N).",
    when: "1등 하나만 필요할 때. '판매량 최다, 동률이면 사전순' → key=lambda kv: (-kv[1], kv[0])에 min.",
    ex: "min(c.items(), key=lambda kv: (-kv[1], kv[0]))[0]",
  },
  deque: {
    name: "collections.deque (덱)",
    sig: "q = deque([시작값들]) / q.append(x) / q.popleft()",
    what: "양쪽 끝에서 넣고 빼기가 모두 빠른 큐. append는 뒤에 추가, popleft는 앞에서 꺼내기 — 둘 다 O(1). 리스트의 pop(0)은 전체를 밀어야 해서 느리다.",
    when: "BFS의 심장. '먼저 넣은 것부터 꺼낸다(선입선출)'가 BFS의 탐색 순서를 보장한다.",
    ex: "q = deque([(0,0)])\nx, y = q.popleft()",
  },
  list_comp: {
    name: "리스트 컴프리헨션",
    sig: "[식 for 변수 in 반복가능]",
    what: "for문을 한 줄로 눌러 담아 리스트를 만든다. [input() for _ in range(n)]은 'n줄을 읽어 리스트로'. _는 '변수값은 안 쓴다'는 관례 표기.",
    when: "N줄 입력 읽기, 2차원 배열 초기화([[0]*m for _ in range(n)]) 등 코테 최빈출 문법.",
    ex: "grid = [input().strip() for _ in range(n)]",
  },
  two_d: {
    name: "2차원 배열 만들기",
    sig: "[[0] * m for _ in range(n)]",
    what: "0으로 채운 n행 m열 표. 주의: [[0]*m]*n으로 만들면 모든 행이 같은 행을 가리켜서 한 칸 바꾸면 전부 바뀌는 대참사가 난다. 반드시 컴프리헨션으로.",
    when: "격자 문제의 방문 체크(visited), 거리 기록(dist) 용.",
    ex: "dist = [[0] * m for _ in range(n)]\ndist[x][y] = 1",
  },
  directions: {
    name: "4방향 이동 관용구",
    sig: "for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):",
    what: "상하좌우 이동량을 튜플 4개로 두고 반복한다. nx, ny = x+dx, y+dy로 다음 칸 좌표를 만든 뒤, 0 <= nx < n and 0 <= ny < m으로 격자 밖 이탈을 막는다.",
    when: "격자 BFS/DFS는 무조건 이 패턴. 그대로 외워서 손이 자동으로 나가야 한다.",
    ex: "if 0 <= nx < n and 0 <= ny < m and grid[nx][ny] == '1':",
  },
  cond_expr: {
    name: "조건부 표현식 (삼항)",
    sig: "A if 조건 else B",
    what: "조건이 참이면 A, 거짓이면 B가 되는 '값'. if문의 한 줄 버전으로, print 안에도 넣을 수 있다.",
    when: "마지막 출력에서 '도달했으면 거리, 아니면 -1' 같은 분기를 짧게 쓸 때.",
    ex: "print(d if d else -1)",
  },
  range_fn: {
    name: "range",
    sig: "range(끝) / range(시작, 끝) / range(시작, 끝, 간격)",
    what: "시작부터 끝-1까지의 정수 나열. range(3)은 0,1,2. range(i+1, n)은 i 다음부터 끝까지 — 조합을 중복 없이 도는 핵심.",
    when: "모든 반복문. 완전탐색의 이중·삼중 for에서 시작값을 '이전 변수+1'로 두면 같은 조합을 두 번 안 센다.",
    ex: "for j in range(i + 1, n):",
  },
  continue_kw: {
    name: "continue (가지치기)",
    sig: "if 조건: continue",
    what: "이번 반복의 나머지를 건너뛰고 다음 반복으로 점프한다. 완전탐색에서 '이 가지는 볼 필요 없음'을 선언하는 도구.",
    when: "더 볼 것도 없이 답이 될 수 없는 경우를 일찍 잘라내 시간을 아낄 때.",
    ex: "if c[i] + c[j] >= m: continue  # 셋째 카드 더하면 무조건 초과",
  },
  floordiv: {
    name: "// 와 % (몫과 나머지)",
    sig: "a // b (몫, 내림) / a %= b (나머지로 갱신)",
    what: "1260 // 500 = 2 (500짜리 2개), 1260 % 500 = 260 (남은 돈). //는 소수점을 버린 정수 몫.",
    when: "동전 거스름돈, '길이 L에서 x짜리 몇 개 나오나'(L//x) — 그리디·이분탐색에서 반복 등장.",
    ex: "cnt += n // coin; n %= coin",
  },
  binsearch: {
    name: "이분탐색 뼈대 (결정 문제)",
    sig: "lo, hi = 1, 최댓값 → while lo <= hi: mid = (lo+hi)//2",
    what: "'답이 x여도 되는가?'라는 예/아니오 질문이 단조(x가 작으면 항상 가능, 크면 불가능)라면, 가능한 최대 x를 반씩 좁혀 log번 만에 찾는다. 가능하면 ans=mid 기록 후 lo=mid+1(더 큰 답 도전), 불가능하면 hi=mid-1.",
    when: "'최대 길이', '최소 시간' 같은 최적화 문제를 '판별 문제'로 뒤집을 수 있을 때. 파라메트릭 서치라고 부른다.",
    ex: "while lo <= hi:\n    mid = (lo + hi) // 2\n    if 가능(mid): ans = mid; lo = mid + 1\n    else: hi = mid - 1",
  },
  sum_gen: {
    name: "sum + 제너레이터식",
    sig: "sum(식 for x in 리스트)",
    what: "각 원소를 식으로 바꾼 값들의 합. 중간 리스트를 안 만들어서 메모리도 아낀다.",
    when: "'케이블마다 몇 조각 나오는지 전부 합쳐라' 같은 집계 한 줄.",
    ex: "sum(c // mid for c in cables)",
  },
  max_builtin: {
    name: "max / min (기본형)",
    sig: "max(a, b) / max(리스트)",
    what: "둘 중(또는 여럿 중) 큰 값. 카데인 알고리즘의 cur = max(x, cur + x)는 '이어붙이기 vs 새 출발' 중 나은 쪽을 고르는 한 줄.",
    when: "DP 점화식에서 '둘 중 최선 선택'을 표현할 때 가장 많이 쓴다.",
    ex: "cur = max(x, cur + x); best = max(best, cur)",
  },
  bisect: {
    name: "bisect.bisect_left",
    sig: "from bisect import bisect_left → i = bisect_left(정렬된리스트, x)",
    what: "정렬된 리스트에서 x가 들어갈 가장 왼쪽 위치를 이분탐색으로 찾는다(O(log N)). 그 위치의 값이 x와 같으면 'x가 존재하고 위치는 i', 다르면 없음.",
    when: "정렬된 데이터에서 검색·삽입 위치 찾기. LIS의 O(N log N) 풀이에서도 핵심 부품.",
    ex: "i = bisect_left(arr, x)\nfound = i < len(arr) and arr[i] == x",
  },
  set_fn: {
    name: "set (집합)",
    sig: "set(리스트) / a - b / x in s / s.add(x)",
    what: "중복 없는 모음. in 검사가 리스트는 O(N)인데 집합은 O(1) — 이 차이가 시간초과를 가른다. a - b는 차집합(a에는 있고 b에는 없는 것).",
    when: "존재 여부 반복 확인, 중복 제거, '출근 - 퇴근 = 남은 사람' 같은 집합 연산.",
    ex: "sorted(arrived - left)",
  },
  sorted_fn: {
    name: "sorted",
    sig: "sorted(반복가능, key=...)",
    what: "sort()와 달리 원본을 안 건드리고 정렬된 새 리스트를 돌려준다. 집합처럼 sort()가 없는 자료형도 정렬 가능.",
    when: "집합·딕셔너리 키를 정렬해서 출력할 때, 원본 보존이 필요할 때.",
    ex: "sorted(words, key=lambda w: (len(w), w))",
  },
  any_fn: {
    name: "any / all",
    sig: "any(식 for x in ...) / all(...)",
    what: "any는 하나라도 참이면 True, all은 전부 참이어야 True. 찾는 즉시 멈춘다(단락 평가).",
    when: "'아직 1이 남은 행이 있나?' 같은 존재 검사 한 줄.",
    ex: "any('1' in row for row in g)",
  },
  tuple_swap: {
    name: "동시 대입 (a, b = b, a+b)",
    sig: "a, b = b, (a + b) % MOD",
    what: "오른쪽을 전부 계산한 뒤 왼쪽에 한꺼번에 대입한다. 임시 변수 없이 두 값을 교체·갱신할 수 있다.",
    when: "피보나치형 DP에서 '직전 두 값만 굴리기'. 배열 없이 O(1) 메모리로 끝난다.",
    ex: "a, b = b, (a + b) % MOD  # dp[i-2], dp[i-1] 갱신",
  },
  mod_arith: {
    name: "나머지 연산 (% MOD)",
    sig: "매 단계마다 % 1_000_000_007",
    what: "경우의 수가 천문학적으로 커지는 문제는 '10^9+7로 나눈 나머지'를 요구한다. 마지막에 한 번이 아니라 더할 때마다 %를 해야 중간값이 폭발하지 않는다.",
    when: "'~를 1,000,000,007로 나눈 나머지를 출력하라'가 보이면 무조건.",
    ex: "b = (a + b) % 1_000_000_007",
  },
  adj_list: {
    name: "인접 리스트 (그래프 표현)",
    sig: "adj = [[] for _ in range(n+1)] → adj[a].append(b)",
    what: "adj[노드] = 그 노드와 연결된 이웃들의 리스트. 무방향 그래프면 양쪽에 서로 추가한다. 인덱스를 1번부터 쓰려고 n+1칸을 만드는 게 관례.",
    when: "그래프 문제의 표준 입력 처리. 이후 BFS/DFS가 adj[u]를 돌며 이웃을 방문한다.",
    ex: "adj[a].append(b); adj[b].append(a)",
  },
  visited: {
    name: "방문 체크 (visited)",
    sig: "seen = [False] * (n + 1)",
    what: "이미 방문한 노드를 표시해 무한 루프와 중복 방문을 막는다. 규칙: 큐에 넣을 때 True로 찍는다(꺼낼 때 찍으면 같은 노드가 큐에 중복으로 쌓인다).",
    when: "모든 BFS/DFS. 연결 요소 세기는 'False인 노드를 만날 때마다 새 그룹 시작+1'.",
    ex: "if not seen[v]: seen[v] = True; q.append(v)",
  },
  strip: {
    name: "문자열.strip()",
    sig: "s.strip()",
    what: "문자열 양끝의 공백·개행을 떼어낸다. readline()으로 읽은 '101111\\n'에서 \\n을 제거할 때 필수.",
    when: "격자를 문자열 그대로 저장할 때. 안 떼면 grid[x][y] 인덱싱이 개행까지 세서 틀어진다.",
    ex: "grid = [input().strip() for _ in range(n)]",
  },
  print_fn: {
    name: "print",
    sig: "print(값) / print('\\n'.join(...))",
    what: "값을 문자열로 바꿔 한 줄 출력(끝에 개행 자동). 숫자든 문자열이든 그대로 넣으면 된다.",
    when: "출력이 수만 줄이면 print 반복 대신 join으로 모아 한 번에 — 출력도 시간에 포함된다.",
    ex: "print(len(tails))",
  },

  // ── SQL ──
  sql_select: {
    name: "SELECT / FROM / WHERE",
    sig: "SELECT 컬럼들 FROM 테이블 WHERE 조건;",
    what: "테이블(FROM)에서 조건(WHERE)에 맞는 행만 걸러, 원하는 컬럼(SELECT)만 뽑는다. 실행 순서는 FROM → WHERE → SELECT라고 생각하면 모든 SQL이 읽힌다.",
    when: "모든 조회의 뼈대. WHERE stock < 10처럼 부등호 조건은 경계값(10 미만 vs 이하)을 문제에서 꼭 확인.",
    ex: "SELECT name, stock FROM products WHERE stock < 10;",
  },
  sql_orderby: {
    name: "ORDER BY",
    sig: "ORDER BY 컬럼1 [DESC], 컬럼2",
    what: "결과를 정렬한다. 기본은 오름차순(ASC), DESC를 붙이면 내림차순. 쉼표로 여러 기준 — 첫 기준이 같을 때만 다음 기준을 본다.",
    when: "출력 순서를 지정하는 모든 문제. '금액 큰 순, 같으면 이름순' = ORDER BY total DESC, name.",
    ex: "ORDER BY stock, name;",
  },
  sql_join: {
    name: "JOIN ... ON",
    sig: "FROM a JOIN b ON b.외래키 = a.기본키",
    what: "두 테이블을 ON 조건으로 짝지어 옆으로 붙인다. (INNER) JOIN은 짝이 있는 행만 남긴다 — 주문 없는 고객이 자동으로 빠지는 이유.",
    when: "정보가 두 테이블에 나뉘어 있을 때. 별칭(customers c)을 붙여 c.name처럼 짧게 쓴다.",
    ex: "FROM customers c JOIN orders o ON o.customer_id = c.id",
  },
  sql_groupby: {
    name: "GROUP BY + 집계함수",
    sig: "SELECT 기준, SUM(x) FROM t GROUP BY 기준",
    what: "같은 값끼리 행을 묶고, 묶음마다 집계함수(SUM 합계 / COUNT(*) 행수 / AVG 평균 / MAX·MIN)를 계산해 묶음당 한 행을 내놓는다.",
    when: "'고객별 총합', '카테고리별 평균' — '~별'이 보이면 GROUP BY.",
    ex: "SELECT c.name, SUM(o.amount) FROM ... GROUP BY c.id",
  },
  sql_having: {
    name: "HAVING",
    sig: "GROUP BY 기준 HAVING 집계조건",
    what: "WHERE는 묶기 전에 행을 거르고, HAVING은 묶은 후에 그룹을 거른다. 집계함수 조건(COUNT(*) >= 2)은 HAVING에만 쓸 수 있다.",
    when: "'메뉴가 2개 이상인 카테고리만' 같은 그룹 조건.",
    ex: "GROUP BY category HAVING COUNT(*) >= 2",
  },
  sql_round_as: {
    name: "ROUND와 AS (별칭)",
    sig: "ROUND(AVG(price)) AS avg_price",
    what: "ROUND는 반올림. AS는 결과 컬럼에 이름을 붙인다 — 문제의 '출력 컬럼' 이름과 맞추는 용도이고, ORDER BY에서 그 별칭을 재사용할 수 있다.",
    when: "출력 컬럼명이 지정된 모든 문제. 채점이 컬럼명을 비교하므로 AS를 빼먹으면 오답.",
    ex: "SELECT category, ROUND(AVG(price)) AS avg_price ...",
  },
  sql_subquery: {
    name: "서브쿼리",
    sig: "WHERE price > (SELECT AVG(price) FROM items)",
    what: "괄호 안 쿼리가 먼저 실행돼 하나의 값(또는 목록)이 되고, 바깥 쿼리가 그 값을 쓴다. '평균'처럼 전체를 봐야 아는 값과 행별 값을 비교할 때 필요하다.",
    when: "'평균보다 비싼', '최댓값과 같은' — 집계값과의 비교 조건.",
    ex: "WHERE price > (SELECT AVG(price) FROM items)",
  },
  sql_rank: {
    name: "RANK() OVER (PARTITION BY ... ORDER BY ...)",
    sig: "RANK() OVER (PARTITION BY 그룹 ORDER BY 기준 DESC)",
    what: "행을 그룹(PARTITION)별로 나눠, 그룹 안에서 기준 순서대로 순위를 매긴다. GROUP BY와 달리 행이 줄지 않고 각 행 옆에 순위가 붙는다. RANK는 동점에 같은 순위를 주고 다음 순위를 건너뛴다(1,2,2,4). 건너뛰지 않는 버전은 DENSE_RANK(1,2,2,3), 동점도 그냥 번호 매기는 건 ROW_NUMBER.",
    when: "'부서별 급여 순위', '그룹 내 상위 N' — 윈도우 함수 문제의 대표 유형.",
    ex: "RANK() OVER (PARTITION BY dept ORDER BY salary DESC) AS salary_rank",
  },
  sql_window_sum: {
    name: "SUM() OVER (ORDER BY ...) — 누적합",
    sig: "SUM(amount) OVER (ORDER BY day) AS running_total",
    what: "ORDER BY 순서대로 '처음부터 현재 행까지'의 합을 각 행에 붙인다. GROUP BY 없이 행마다 누적값이 생기는 게 포인트.",
    when: "누적 매출, 누적 카운트. PARTITION BY를 추가하면 '그룹별 누적'도 된다.",
    ex: "SELECT day, amount, SUM(amount) OVER (ORDER BY day) AS running_total",
  },
};

/* ── 문제별 해설 ─────────────────────────────────────
   concepts: [이름, 설명] / blocks: [코드, 해설] / funcs: FUNC_DICT 키 */
const GUIDE = {
  1: {
    concepts: [
      ["다중 기준 정렬", "정렬 기준이 2개 이상이면 튜플 (기준1, 기준2)로 만들어 정렬한다. 파이썬이 알아서 기준1 → 기준2 순으로 비교해준다."],
      ["음수 트릭", "'점수는 내림차순 + 이름은 오름차순'처럼 방향이 섞이면, 숫자에 -를 붙여 (-점수, 이름)으로 저장하고 그냥 오름차순 정렬한다."],
    ],
    blocks: [
      ["import sys\ninput = sys.stdin.readline",
       "빠른 입력 관용구. N이 10만이면 기본 input()은 시간 초과 위험이 있어서 반사적으로 붙인다."],
      ["n, k = map(int, input().split())",
       "첫 줄 '4 2'를 공백으로 쪼개('4','2') 각각 int로 바꿔 n=4, k=2에 동시 대입."],
      ["rows = []\nfor _ in range(n):\n    name, score = input().split()\n    rows.append((-int(score), name))",
       "N줄을 읽으며 (-점수, 이름) 튜플로 저장. 점수에 -를 붙였으므로 나중에 오름차순 정렬하면 점수 높은 사람이 앞에 온다. 점수가 같으면 튜플의 둘째 원소인 이름(문자열 오름차순)으로 자동 비교 — 문제의 tie-break 조건이 공짜로 해결된다."],
      ["rows.sort()",
       "튜플 비교 규칙대로 정렬. (-95,'alex') < (-95,'blair') < (-90,'casey') 순."],
      ["print('\\n'.join(name for _, name in rows[:k]))",
       "앞에서 k개만 잘라(rows[:k]) 이름만 뽑아('_'는 점수 무시) 개행으로 이어 한 번에 출력. print를 k번 부르는 것보다 빠르다."],
    ],
    funcs: ["input_readline", "map_int", "split", "list_fn", "neg_trick", "tuple_compare", "sort_key", "slice", "join", "print_fn"],
  },
  2: {
    concepts: [
      ["빈도 세기 = Counter", "'가장 많이 팔린 것'은 세는 문제다. Counter에 리스트를 넣으면 {값: 횟수}가 나온다."],
      ["정렬 없이 1등 뽑기", "1등 하나만 필요하면 정렬(N log N) 대신 min/max(N)에 key를 줘서 뽑는다."],
    ],
    blocks: [
      ["import sys\nfrom collections import Counter\ndata = sys.stdin.read().split()",
       "입력 전체를 한 번에 읽어 토큰 리스트로. data[0]이 N, data[1]부터가 책 제목들."],
      ["n = int(data[0])\nc = Counter(data[1:1 + n])",
       "제목 구간만 슬라이스해서 Counter에 → {'apple': 2, 'banana': 2, 'cherry': 1}."],
      ["print(min(c.items(), key=lambda kv: (-kv[1], kv[0]))[0])",
       "c.items()의 각 (제목, 횟수) 쌍을 (-횟수, 제목) 기준으로 비교해 최솟값을 찾는다. -횟수가 가장 작다 = 횟수가 가장 많다. 횟수가 같으면 제목 사전순으로 앞선 것. [0]으로 제목만 꺼내 출력."],
    ],
    funcs: ["read_split", "counter", "slice", "min_max_key", "neg_trick", "tuple_compare", "print_fn"],
  },
  3: {
    concepts: [
      ["BFS = 최단거리", "가중치 없는 격자/그래프에서 최단거리는 무조건 BFS. 가까운 칸부터 물결처럼 퍼지므로, 어떤 칸에 처음 도달했을 때의 거리가 곧 최단거리다."],
      ["거리 배열이 방문 체크를 겸함", "dist가 0이면 미방문, 0이 아니면 방문+거리. 배열 하나로 두 역할."],
    ],
    blocks: [
      ["n, m = map(int, input().split())\ngrid = [input().strip() for _ in range(n)]",
       "격자를 문자열 리스트로 저장. strip()으로 개행 제거 필수. grid[x][y]로 한 글자씩 접근."],
      ["dist = [[0] * m for _ in range(n)]\ndist[0][0] = 1\nq = deque([(0, 0)])",
       "거리 표를 0으로 초기화하고 시작 칸을 1로(문제가 '칸 수'를 세므로 출발 칸 포함 = 1부터). 큐에 시작 좌표를 넣는다."],
      ["while q:\n    x, y = q.popleft()\n    for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):\n        nx, ny = x + dx, y + dy",
       "큐가 빌 때까지: 맨 앞 칸을 꺼내(popleft — 선입선출이 BFS의 핵심) 상하좌우 4칸의 좌표를 만든다."],
      ["        if 0 <= nx < n and 0 <= ny < m and grid[nx][ny] == '1' and dist[nx][ny] == 0:\n            dist[nx][ny] = dist[x][y] + 1\n            q.append((nx, ny))",
       "격자 안이고 + 길('1')이고 + 미방문이면: 현재 거리+1을 기록하고 큐에 추가. 이 세 조건 체크가 격자 BFS의 전부다."],
      ["print(dist[n-1][m-1] if dist[n-1][m-1] else (1 if n == m == 1 else -1))",
       "도착 칸 거리가 기록됐으면 그 값, 0이면 도달 실패로 -1. 단 1×1 격자는 시작=도착이라 1을 출력하는 예외 처리."],
    ],
    funcs: ["deque", "list_comp", "two_d", "directions", "strip", "cond_expr", "map_int"],
  },
  6: {
    concepts: [
      ["완전탐색(브루트포스)", "가능한 모든 경우를 다 시도한다. N이 작을 때(대략 연산 1억 번 이하)만 허용되는 정공법. 여기선 N≤100이라 3장 조합이 최대 약 16만 개 — 여유롭다."],
      ["중복 없는 조합 만들기", "이중·삼중 for에서 안쪽 범위를 range(i+1, n), range(j+1, n)으로 시작하면 (1,2,3)과 (3,2,1)을 두 번 세는 일이 없다."],
      ["가지치기", "두 장 합이 이미 M 이상이면 셋째 장(1 이상)을 더하는 순간 무조건 초과 → 안쪽 루프를 통째로 건너뛴다."],
    ],
    blocks: [
      ["n, m = map(int, input().split())\nc = list(map(int, input().split()))",
       "첫 줄에서 N, M을, 둘째 줄에서 카드 N장을 정수 리스트로."],
      ["best = 0\nfor i in range(n):\n    for j in range(i + 1, n):",
       "i번째, 그다음부터 j번째 — 시작 인덱스를 어긋나게 해서 같은 카드 재사용과 순서만 다른 중복 조합을 원천 차단."],
      ["        if c[i] + c[j] >= m:\n            continue  # 세 번째 카드(1 이상)를 더하면 무조건 M 초과",
       "가지치기. 이 한 줄이 없어도 정답은 같지만, 불필요한 안쪽 루프를 잘라 시간을 아낀다."],
      ["        for k in range(j + 1, n):\n            s = c[i] + c[j] + c[k]\n            if best < s <= m: best = s",
       "세 장 합 s가 '지금까지 최고보다 크고 M 이하'면 갱신. best < s <= m은 두 비교를 한 번에 쓰는 파이썬 연쇄 비교."],
      ["print(best)", "다 돌고 남은 최고 기록 출력."],
    ],
    funcs: ["map_int", "range_fn", "continue_kw", "list_fn", "print_fn"],
  },
  7: {
    concepts: [
      ["그리디(탐욕법)", "매 순간 가장 좋아 보이는 선택(가장 큰 동전부터)을 반복한다. 이 동전 체계(500·100·50·10·5·1)는 큰 단위가 작은 단위의 배수라 그리디가 항상 최적임이 보장된다."],
      ["몫과 나머지 반복", "각 동전으로 '몇 개 쓸 수 있나(//)' 세고, '남은 금액(%)'으로 갱신하는 두 줄이 전부."],
    ],
    blocks: [
      ["n = int(input())\ncnt = 0",
       "금액 하나 입력. 짧은 입력이라 sys.stdin도 필요 없다."],
      ["for coin in (500, 100, 50, 10, 5, 1):\n    cnt += n // coin\n    n %= coin",
       "큰 동전부터: 1260원이면 500으로 2개(cnt+=2), 남은 260원(n=260) → 100으로 2개, 남은 60 → 50으로 1개, 남은 10 → 10으로 1개, 남은 0. 몫은 개수, 나머지는 다음 동전의 몫감."],
      ["print(cnt)", "총 개수 6 출력."],
    ],
    funcs: ["int_fn", "floordiv", "range_fn", "print_fn"],
  },
  8: {
    concepts: [
      ["활동 선택 문제", "'겹치지 않게 최대한 많이'는 그리디의 대표 유형. 핵심 정리: 끝나는 시간이 가장 이른 것부터 고르면 항상 최적이다 — 일찍 끝날수록 뒤에 더 많은 기회가 남기 때문."],
      ["끝 시간 기준 정렬 후 한 번 훑기", "정렬(N log N) + 스캔(N)이면 끝. end 변수 하나로 '마지막으로 수락한 회의가 끝난 시각'을 들고 다닌다."],
    ],
    blocks: [
      ["n = int(input())\niv = [tuple(map(int, input().split())) for _ in range(n)]",
       "N개의 (시작, 종료) 튜플 리스트. 컴프리헨션으로 N줄을 한 줄에 읽는다."],
      ["iv.sort(key=lambda x: (x[1], x[0]))",
       "끝나는 시간(x[1]) 오름차순으로 정렬 — 그리디의 핵심 준비. 끝이 같으면 시작 시간순(결과엔 영향 없지만 안정적)."],
      ["cnt, end = 0, -1\nfor s, e in iv:\n    if s >= end:\n        cnt += 1\n        end = e",
       "차례로 보면서 시작(s)이 직전 수락 건의 종료(end) 이상이면 수락. '끝나는 시각에 바로 시작 가능' 조건이 s >= end의 등호다. 수락하면 end를 갱신."],
      ["print(cnt)", "수락한 개수 출력."],
    ],
    funcs: ["sort_key", "tuple_compare", "list_comp", "map_int", "print_fn"],
  },
  9: {
    concepts: [
      ["이분탐색(존재 검색)", "정렬된 배열에서는 가운데를 보고 절반을 버리는 걸 반복해 log₂N번 만에 찾는다. 10만 개면 17번. 직접 구현 대신 표준 라이브러리 bisect를 쓰는 게 실수도 없고 빠르다."],
      ["bisect_left의 두 가지 정보", "돌려준 위치 i는 '있다면 여기 있어야 함'이므로, arr[i] == x인지 확인하면 존재 여부와 위치를 동시에 얻는다."],
    ],
    blocks: [
      ["data = sys.stdin.buffer.read().split()\nn = int(data[0])\narr = list(map(int, data[1:1 + n]))\nq = int(data[1 + n])",
       "토큰 20만 개 규모라 가장 빠른 buffer.read로 전부 읽고 인덱스로 잘라 쓴다. arr 구간, q 위치를 계산해서 슬라이스."],
      ["out = []\nfor tok in data[2 + n:2 + n + q]:\n    x = int(tok)\n    i = bisect_left(arr, x)\n    out.append(str(i) if i < n and arr[i] == x else '-1')",
       "질의마다: bisect_left로 후보 위치 i를 얻고 → i가 범위 안이고 그 자리 값이 x면 위치, 아니면 -1. 결과는 문자열로 리스트에 모은다."],
      ["print('\\n'.join(out))",
       "10만 줄을 print 10만 번 하면 그것만으로 느려진다. join으로 한 번에."],
    ],
    funcs: ["buffer_read", "bisect", "slice", "cond_expr", "join", "list_fn"],
  },
  10: {
    concepts: [
      ["파라메트릭 서치 (답을 이분탐색)", "'최대 길이 x'를 직접 구하는 대신 '길이 x로 N개를 만들 수 있나?'라는 예/아니오 문제로 뒤집는다. x가 작을수록 쉬워지는 단조성이 있으므로 이분탐색이 가능하다."],
      ["판별 함수", "길이 x일 때 만들 수 있는 개수 = 각 케이블의 (길이//x) 합. 이 합이 N 이상이면 '가능'."],
      ["범위 갱신 규칙", "가능하면 답 후보로 기록하고 더 큰 쪽(lo=mid+1) 도전, 불가능하면 작은 쪽(hi=mid-1)으로 후퇴. while lo <= hi가 끝나면 ans가 최댓값."],
    ],
    blocks: [
      ["k, n = map(int, input().split())\ncables = [int(input()) for _ in range(k)]",
       "케이블 K개의 길이를 리스트로."],
      ["lo, hi, ans = 1, max(cables), 1",
       "답의 탐색 범위: 최소 1, 최대 '가장 긴 케이블 길이'. ans는 문제 보장(길이 1은 항상 가능)에 맞춰 1로 시작."],
      ["while lo <= hi:\n    mid = (lo + hi) // 2\n    if sum(c // mid for c in cables) >= n:\n        ans = mid; lo = mid + 1\n    else:\n        hi = mid - 1",
       "가운데 길이 mid로 판별: 조각 수 합이 n 이상이면 mid는 가능한 답 → 기록하고 더 긴 길이에 도전. 부족하면 길이를 줄인다. 범위가 뒤집힐 때까지 반복하면 log₂(20억)≈31번 만에 수렴."],
      ["print(ans)", "기록된 마지막 '가능한 최대 길이' 출력."],
    ],
    funcs: ["binsearch", "sum_gen", "floordiv", "max_builtin", "list_comp", "print_fn"],
  },
  11: {
    concepts: [
      ["DP의 최소 단위", "'n번째 답 = 이전 답들의 조합'이면 DP다. n계단에 오는 방법은 (n-1)에서 1칸 or (n-2)에서 2칸뿐이므로 dp[n] = dp[n-1] + dp[n-2] — 피보나치와 같은 구조."],
      ["변수 두 개로 굴리기", "dp 배열 전체를 저장할 필요 없이 직전 두 값만 있으면 된다. a, b = b, a+b 한 줄로 갱신 — 메모리 O(1)."],
      ["매 단계 % MOD", "경우의 수가 지수적으로 커지므로 더할 때마다 나머지를 취해 숫자 크기를 눌러둔다."],
    ],
    blocks: [
      ["n = int(input())\nMOD = 1_000_000_007",
       "밑줄은 자릿수 구분용(가독성) — 값은 그냥 1000000007."],
      ["a, b = 1, 2\nif n == 1: print(1)\nelif n == 2: print(2)",
       "기저 사례: 1계단 1가지(1), 2계단 2가지(1+1, 2). a=dp[1], b=dp[2]."],
      ["else:\n    for _ in range(3, n + 1):\n        a, b = b, (a + b) % MOD\n    print(b)",
       "3계단부터 n까지: 새 값 = 직전 두 값의 합(mod). 동시 대입이라 임시 변수가 필요 없다. 루프가 끝나면 b가 dp[n]."],
    ],
    funcs: ["tuple_swap", "mod_arith", "range_fn", "int_fn", "print_fn"],
  },
  12: {
    concepts: [
      ["카데인 알고리즘", "최대 연속 부분합의 정석. 각 위치에서 '여기서 끝나는 최대 합(cur)'을 유지하며 한 번만 훑는다 — O(N)."],
      ["이어붙이기 vs 새 출발", "cur = max(x, cur + x): 지금까지의 합에 x를 이어붙이는 게 나은지, 짐(음수 누적)을 버리고 x부터 새로 시작하는 게 나은지를 매 칸 결정한다."],
      ["전부 음수인 경우", "best를 0이 아니라 a[0]으로 시작해야 한다. 0으로 시작하면 '아무것도 안 고름'이 답이 되는 오류 — 문제는 '하루 이상'을 요구한다."],
    ],
    blocks: [
      ["n = int(input())\na = list(map(int, input().split()))",
       "손익 N개를 리스트로."],
      ["best = cur = a[0]",
       "첫 원소로 초기화. cur = '현재 위치에서 끝나는 구간의 최대 합', best = '전체 최고 기록'."],
      ["for x in a[1:]:\n    cur = max(x, cur + x)\n    best = max(best, cur)",
       "둘째 원소부터: cur+x(이어붙이기)와 x(새 출발) 중 큰 쪽이 새 cur. 예: -2, 3에서 cur는 max(3, -2+3)=3 — 앞의 -2를 버린다. best는 매번 최고치 갱신."],
      ["print(best)", "한 번 훑고 끝. N=10만도 순식간."],
    ],
    funcs: ["max_builtin", "slice", "map_int", "list_fn", "print_fn"],
  },
  13: {
    concepts: [
      ["LIS (최장 증가 부분수열)", "순서를 유지하며 골라낸 오름차순 수열의 최대 길이. O(N²) DP가 기본형이지만, 여기 답안은 더 빠른 O(N log N) 풀이다."],
      ["tails 배열의 의미", "tails[i] = '길이 i+1짜리 증가 수열을 만들 때 가능한 가장 작은 끝값'. 이 배열은 항상 정렬 상태가 유지되므로 이분탐색이 가능하다. 주의: tails 자체가 실제 수열은 아니고, 길이(len)만 정답이다."],
      ["갱신 규칙", "새 값 x가 tails의 모든 값보다 크면 뒤에 붙여 길이 연장. 아니면 x가 들어갈 자리(bisect_left)의 값을 x로 교체 — 같은 길이를 더 작은 끝값으로 유지해 미래의 연장 가능성을 키운다."],
    ],
    blocks: [
      ["n = int(input())\na = list(map(int, input().split()))\ntails = []",
       "수열 입력, tails는 빈 리스트로 시작."],
      ["for x in a:\n    i = bisect_left(tails, x)\n    if i == len(tails): tails.append(x)\n    else: tails[i] = x",
       "각 원소 x에 대해: 들어갈 위치를 이분탐색. 맨 끝이면(모두보다 크면) append로 길이+1, 아니면 그 자리 값을 x로 교체. bisect_left라서 같은 값은 연장이 아니라 교체 — '엄격히 증가' 조건이 이걸로 지켜진다."],
      ["print(len(tails))",
       "10 20 10 30 20 50 → tails 변화: [10] → [10,20] → [10,20](10이 교체) → [10,20,30] → [10,20,30](20 교체) → [10,20,30,50]. 길이 4."],
    ],
    funcs: ["bisect", "list_fn", "map_int", "print_fn"],
  },
  14: {
    concepts: [
      ["연결 요소(Connected Component)", "서로 이어진 노드 덩어리. '아직 방문 안 한 노드에서 BFS를 시작할 때마다 새 덩어리 하나'가 세는 원리의 전부다."],
      ["인접 리스트 + 방문 배열", "그래프 문제의 기본 세팅. adj[u]에 이웃을 담고, seen으로 중복 방문을 막는다."],
    ],
    blocks: [
      ["n, m = map(int, input().split())\nadj = [[] for _ in range(n + 1)]\nfor _ in range(m):\n    a, b = map(int, input().split())\n    adj[a].append(b); adj[b].append(a)",
       "노드 번호가 1부터라 n+1칸. 무방향이므로 양쪽 모두에 추가 — 한쪽만 넣는 게 그래프 문제 최다 실수."],
      ["seen = [False] * (n + 1)\ncnt = 0\nfor s in range(1, n + 1):\n    if seen[s]: continue\n    cnt += 1",
       "1번부터 N번까지 훑다가 미방문 노드를 만나면 = 새 동아리 발견. 카운트하고 그 덩어리 전체를 아래 BFS로 방문 처리한다."],
      ["    seen[s] = True\n    q = deque([s])\n    while q:\n        u = q.popleft()\n        for v in adj[u]:\n            if not seen[v]:\n                seen[v] = True; q.append(v)",
       "표준 BFS. '큐에 넣을 때 seen 체크'가 규칙 — 꺼낼 때 체크하면 같은 노드가 큐에 여러 번 들어가 느려진다. 이 BFS가 끝나면 s와 이어진 전원이 방문 완료."],
      ["print(cnt)", "BFS를 새로 시작한 횟수 = 동아리 수."],
    ],
    funcs: ["adj_list", "visited", "deque", "continue_kw", "range_fn", "print_fn"],
  },
  15: {
    concepts: [
      ["멀티소스 BFS", "감염원이 여러 개면 전부를 거리 0으로 큐에 미리 넣고 BFS 한 번만 돌린다. 그러면 모든 칸에 '가장 가까운 감염원으로부터의 거리'가 계산된다. 감염원마다 따로 돌리는 것보다 압도적으로 빠르다."],
      ["답 = 마지막으로 꺼낸 칸의 거리", "BFS는 거리 순으로 꺼내므로, 마지막에 꺼낸 칸의 d가 전체가 감염되는 데 걸린 일수다."],
      ["불가능 판정", "BFS가 끝나고도 '1'이 남아 있으면 벽에 막혀 도달 못 한 것 → -1."],
    ],
    blocks: [
      ["n, m = map(int, input().split())\ng = [list(input().strip()) for _ in range(n)]",
       "이번엔 list()로 감싸 문자 리스트로 저장 — 감염 표시(g[nx][ny]='2')를 위해 수정 가능해야 하기 때문. 문자열은 수정 불가."],
      ["q = deque()\nfor i in range(n):\n    for j in range(m):\n        if g[i][j] == '2': q.append((i, j, 0))",
       "모든 감염원을 (좌표, 날짜 0)으로 큐에 선적재 — 멀티소스의 핵심 한 수."],
      ["days = 0\nwhile q:\n    x, y, d = q.popleft()\n    days = d\n    for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):\n        nx, ny = x + dx, y + dy\n        if 0 <= nx < n and 0 <= ny < m and g[nx][ny] == '1':\n            g[nx][ny] = '2'; q.append((nx, ny, d + 1))",
       "정상 상자('1')만 감염시키고 d+1과 함께 큐에. 격자 자체를 '2'로 바꿔서 방문 체크를 겸한다(별도 visited 불필요). days는 꺼낼 때마다 덮어써서 자연히 마지막 거리가 남는다."],
      ["print(-1 if any('1' in row for row in g) else days)",
       "'1'이 한 칸이라도 남았으면 -1, 아니면 걸린 일수. 처음부터 '1'이 없었다면 days는 0."],
    ],
    funcs: ["deque", "directions", "any_fn", "list_comp", "strip", "cond_expr"],
  },
  16: {
    concepts: [
      ["집합 차집합", "'출근 명단 - 퇴근 명단 = 남은 사람'. 집합으로 바꾸면 뺄셈 연산자 하나로 끝난다."],
      ["왜 리스트가 아니라 set인가", "리스트에서 'x가 퇴근했나'를 매번 확인하면 O(N×M)=100억 번 — 시간 초과. 집합은 확인이 O(1)이라 전체 O(N+M)."],
    ],
    blocks: [
      ["data = sys.stdin.read().split()\nn, m = int(data[0]), int(data[1])",
       "이름에 공백이 없으므로 전체를 토큰으로 읽어도 안전."],
      ["arrived = set(data[2:2 + n])\nleft = set(data[2 + n:2 + n + m])",
       "출근 구간과 퇴근 구간을 각각 잘라 집합으로."],
      ["print('\\n'.join(sorted(arrived - left)))",
       "차집합 → sorted로 사전순 정렬(집합은 순서가 없으므로 필수) → join으로 한 번에 출력. 세 함수를 겹쳐 한 줄."],
    ],
    funcs: ["read_split", "set_fn", "sorted_fn", "slice", "join"],
  },
  17: {
    concepts: [
      ["중복 제거 + 다중 기준 정렬", "set으로 중복을 없애고, sorted의 key에 (길이, 단어) 튜플을 줘서 '짧은 것부터, 같으면 사전순'을 한 줄로 처리한다."],
    ],
    blocks: [
      ["data = sys.stdin.read().split()\nn = int(data[0])",
       "단어 10만 개 — 전체 읽기가 안전하고 빠르다."],
      ["words = sorted(set(data[1:1 + n]), key=lambda w: (len(w), w))",
       "set()이 중복 제거, sorted가 정렬. key가 돌려주는 (길이, 단어) 튜플 비교 규칙에 따라 길이 우선 → 사전순. 이 한 줄이 이 문제의 전부다."],
      ["print('\\n'.join(words))", "결과 일괄 출력."],
    ],
    funcs: ["read_split", "set_fn", "sorted_fn", "sort_key", "tuple_compare", "join"],
  },
  4: {
    concepts: [
      ["JOIN으로 두 테이블 잇기", "이름은 customers에, 금액은 orders에 있다. o.customer_id = c.id로 짝을 맞춰야 한 줄에 이름+금액이 모인다."],
      ["INNER JOIN의 부수 효과", "짝이 없는 행은 자동 탈락 — '주문한 적 있는 고객만'이라는 조건이 JOIN만으로 충족된다(choi는 주문이 없어 사라짐)."],
      ["GROUP BY 후 집계", "고객별로 묶어 SUM. GROUP BY c.id로 묶는 것이 이름으로 묶는 것보다 안전(동명이인 대비)."],
    ],
    blocks: [
      ["SELECT c.name, SUM(o.amount) AS total_amount",
       "출력 컬럼: 이름과, 그룹(고객)별 금액 합계. AS로 문제에서 요구한 컬럼명 total_amount를 붙인다 — 채점이 컬럼명을 본다."],
      ["FROM customers c JOIN orders o ON o.customer_id = c.id",
       "customers에 c, orders에 o라는 별칭. ON 조건이 '이 주문은 이 고객의 것'이라는 연결고리."],
      ["GROUP BY c.id ORDER BY total_amount DESC, c.name;",
       "고객 id별로 묶고 → 합계 내림차순, 동액이면 이름 오름차순. ORDER BY에서 SELECT의 별칭(total_amount)을 그대로 쓸 수 있다."],
    ],
    funcs: ["sql_select", "sql_join", "sql_groupby", "sql_round_as", "sql_orderby"],
  },
  5: {
    concepts: [
      ["윈도우 함수 = 행을 유지한 채 계산", "GROUP BY는 그룹당 한 행으로 접지만, OVER(...)는 모든 행을 남기면서 각 행에 계산 결과(순위)를 붙인다."],
      ["PARTITION BY = 그룹 나누기", "부서별로 칸을 나눠 그 안에서만 순위를 매긴다. ORDER BY salary DESC가 '높은 급여가 1등' 방향."],
      ["RANK vs DENSE_RANK", "RANK: 동점이면 같은 순위, 다음 순위는 건너뜀(1,2,2,4). DENSE_RANK: 안 건너뜀(1,2,2,3). 문제가 어느 쪽을 요구하는지 반드시 확인."],
    ],
    blocks: [
      ["SELECT dept, name, salary,\n       RANK() OVER (PARTITION BY dept ORDER BY salary DESC) AS salary_rank",
       "각 행에: 부서 안에서 급여 내림차순 순위를 계산해 salary_rank로 붙인다. data 부서 5200 동점 2명은 둘 다 2위, 다음 사람은 4위."],
      ["FROM employees ORDER BY dept, salary_rank, name;",
       "출력 정렬은 별도로 지정해야 한다 — OVER 안의 ORDER BY는 순위 계산용일 뿐 출력 순서를 보장하지 않는다."],
    ],
    funcs: ["sql_rank", "sql_select", "sql_orderby", "sql_round_as"],
  },
  18: {
    concepts: [
      ["WHERE 조건과 경계값", "'10 미만'은 < 10. '이하(<=)'와 헷갈리면 바로 오답 — 채점 데이터에 정확히 경계(9와 10)가 심어져 있다."],
    ],
    blocks: [
      ["SELECT name, stock FROM products WHERE stock < 10",
       "products에서 재고 10 미만 행만 걸러 이름·재고만 뽑는다. glue(10)는 탈락, tape(9)는 포함."],
      ["ORDER BY stock, name;",
       "재고 오름차순, 같으면(pen과 clip 모두 3) 이름 오름차순."],
    ],
    funcs: ["sql_select", "sql_orderby"],
  },
  19: {
    concepts: [
      ["WHERE vs HAVING", "묶기 전 행 필터는 WHERE, 묶은 후 그룹 필터는 HAVING. 'COUNT(*) >= 2' 같은 집계 조건은 HAVING 자리다."],
      ["집계 결과 가공", "AVG는 소수가 나올 수 있어 ROUND로 반올림. 출력 컬럼명은 AS로 맞춘다."],
    ],
    blocks: [
      ["SELECT category, ROUND(AVG(price)) AS avg_price\nFROM menu GROUP BY category",
       "카테고리별로 묶어 평균 가격을 반올림. beverage처럼 1개짜리 카테고리도 아직은 그룹으로 존재한다."],
      ["HAVING COUNT(*) >= 2",
       "묶인 그룹 중 행이 2개 이상인 것만 통과 — beverage(1개)가 여기서 탈락. 이 줄을 WHERE에 쓰면 문법 오류다."],
      ["ORDER BY avg_price DESC, category;",
       "평균가 비싼 순, 같으면 카테고리 이름순."],
    ],
    funcs: ["sql_groupby", "sql_having", "sql_round_as", "sql_orderby"],
  },
  20: {
    concepts: [
      ["서브쿼리로 기준값 만들기", "'평균보다 비싼'에서 평균은 전체를 봐야 나오는 값. 괄호 안 SELECT가 먼저 평균 하나를 계산하고, 바깥 WHERE가 행마다 그 값과 비교한다."],
      ["> 와 >= 의 차이", "평균(40000)과 정확히 같은 fan은 '평균보다 비싼'이 아니므로 제외 — 등호 포함 여부가 채점 포인트다."],
    ],
    blocks: [
      ["SELECT name, price FROM items\nWHERE price > (SELECT AVG(price) FROM items)",
       "안쪽 쿼리: 전체 평균 40000. 바깥 쿼리: 가격이 그보다 큰 행만(ssd, ram). 같은 테이블을 두 번 읽는 게 어색해 보여도 표준 패턴이다."],
      ["ORDER BY price DESC, name;",
       "비싼 순, 같으면 이름순."],
    ],
    funcs: ["sql_subquery", "sql_select", "sql_orderby"],
  },
  21: {
    concepts: [
      ["누적합 윈도우", "SUM(...) OVER (ORDER BY day)는 'day 순서로 여기까지의 합'을 각 행에 붙인다. GROUP BY 없이 행 수가 그대로인 게 특징."],
      ["프레임 개념(참고)", "ORDER BY가 있는 SUM OVER의 기본 범위는 '처음부터 현재 행까지'라 그대로 누적합이 된다."],
    ],
    blocks: [
      ["SELECT day, amount, SUM(amount) OVER (ORDER BY day) AS running_total",
       "1일 12000 → 12000, 3일 8000 → 20000, 4일 15000 → 35000처럼 행마다 누적값이 붙는다."],
      ["FROM sales ORDER BY day;",
       "출력 순서도 day 오름차순으로 명시 — 윈도우의 ORDER BY와 출력 정렬은 별개다."],
    ],
    funcs: ["sql_window_sum", "sql_select", "sql_orderby"],
  },
};

/* ── 직관 보강: 함수별 한 줄 비유(ana) + 입력→출력 눈 예시(io) ── */
const FUNC_INTUIT = {
  input_readline: { ana: "일반 창구(input) 대신 대량 우편 전용 창구로 받기 — 하는 일은 같은데 훨씬 빠르다",
    io: "'5\\n'  ──int(input())──▶  5" },
  read_split: { ana: "택배를 하나씩 뜯지 않고, 전부 쏟아서 한 줄로 세워놓기",
    io: "'3\\na b\\nc'  ──read().split()──▶  ['3','a','b','c']" },
  buffer_read: { ana: "read().split()의 스포츠카 버전 — 포장(문자열 변환)도 생략",
    io: "b'3 7'  ──buffer.read().split()──▶  [b'3', b'7']  → int(b'3')=3" },
  split: { ana: "문자열을 공백 가위로 싹둑싹둑",
    io: "'kim 90'  ──split()──▶  ['kim', '90']" },
  map_int: { ana: "컨베이어 벨트: 지나가는 것마다 int 도장을 찍는다",
    io: "['4','2']  ──map(int)──▶  4, 2   (n, k = 로 바로 받기)" },
  int_fn: { ana: "글자로 된 숫자를 진짜 숫자로 — '9'<'10'이 거짓이 되는 사고 방지",
    io: "'42\\n'  ──int──▶  42" },
  list_fn: { ana: "순서대로 쌓는 서랍장. append는 맨 아래 칸 추가",
    io: "[] ──append(3)──▶ [3] ──append(7)──▶ [3, 7]" },
  sort_key: { ana: "key는 '무엇을 보고 줄 세울지' 정하는 심판",
    io: "[(1,4),(3,5),(0,6)] ──sort(key=끝시간)──▶ [(1,4),(3,5),(0,6)]  (끝 4<5<6)" },
  neg_trick: { ana: "키 큰 순 줄세우기가 필요하면, 키에 -를 붙여서 '작은 순'으로 세운다",
    io: "[90, 95] ──부호 뒤집기──▶ [-90, -95] ──오름차순──▶ -95(=95점)가 1등" },
  tuple_compare: { ana: "사전 찾기: 첫 글자 비교, 같으면 둘째 글자로",
    io: "(-95,'alex') vs (-95,'blair')  ──첫 값 동점──▶  'alex'<'blair'로 판정" },
  join: { ana: "구슬(문자열들)을 실(구분자)로 꿰기",
    io: "['a','b','c']  ──'\\n'.join──▶  'a\\nb\\nc'  (한 번에 3줄 출력)" },
  slice: { ana: "식빵에서 앞 k장만 잘라 가져오기 (원본은 그대로)",
    io: "[10,20,30,40] ──[:2]──▶ [10,20]" },
  counter: { ana: "자동 계수기: 넣기만 하면 종류별 개수표가 나온다",
    io: "['a','b','a']  ──Counter──▶  {'a': 2, 'b': 1}" },
  min_max_key: { ana: "전교 1등만 필요하면 전교생을 줄 세울(정렬) 필요 없이 한 바퀴 돌며 찾으면 된다",
    io: "{'a':2,'b':2,'c':1}.items() ──min(key=(-개수,이름))──▶ ('a', 2)" },
  deque: { ana: "은행 대기줄: 뒤로 서고(append) 앞에서 빠진다(popleft)",
    io: "[1,2,3] ──popleft()──▶ 1을 꺼내고 [2,3] 남음" },
  list_comp: { ana: "for문 도시락: 반복해서 만든 결과를 한 줄에 포장",
    io: "[x*2 for x in [1,2,3]]  ──▶  [2, 4, 6]" },
  two_d: { ana: "모눈종이 펴기. 곱셈(*n)으로 만들면 먹지 복사본이라 한 칸 쓰면 전부 번진다",
    io: "[[0]*3 for _ in range(2)]  ──▶  [[0,0,0], [0,0,0]]" },
  directions: { ana: "동서남북 나침반을 주머니에 넣고 다니기",
    io: "(1,2)에서 ──4방향──▶ (2,2) (0,2) (1,3) (1,1)" },
  cond_expr: { ana: "'있으면 그거, 없으면 저거' 한 줄 분기",
    io: "d=15 → print(d if d else -1) ──▶ 15  /  d=0 → -1" },
  range_fn: { ana: "번호표 뽑기 기계. 시작을 i+1로 두면 앞사람 번호는 다시 안 뽑는다",
    io: "range(2, 5)  ──▶  2, 3, 4" },
  continue_kw: { ana: "'이 후보는 탈락 확정, 다음!' 하고 건너뛰기",
    io: "합이 이미 초과 ──continue──▶ 안쪽 루프 자체를 생략" },
  floordiv: { ana: "1260원을 500원 동전으로: 몇 개(//)와 잔돈(%)",
    io: "1260 // 500 = 2,  1260 % 500 = 260" },
  binsearch: { ana: "업다운 게임: '이 길이 가능?'을 물어 절반씩 좁히기",
    io: "1~802 → 401(불가)→ 1~400 → 200(가능, 기록)→ 201~400 → … ──▶ 답 200" },
  sum_gen: { ana: "각자 계산시키고 합계만 받기",
    io: "cables=[802,743,457,539], mid=200 → 4+3+2+2 = 11조각" },
  max_builtin: { ana: "둘 놓고 큰 쪽 집기",
    io: "cur = max(3, -2+3)  ──▶  3  (이어붙이기 1 vs 새출발 3)" },
  bisect: { ana: "사전에서 단어 찾기: 가운데 펴고 앞/뒤 절반 버리기를 반복",
    io: "[2,4,6,8,10]에서 6 ──bisect_left──▶ 위치 2 (arr[2]==6 → 존재)" },
  set_fn: { ana: "출석부 명단: '있나?' 확인이 즉시 끝난다. 빼기는 명단 차감",
    io: "{'kim','lee','park'} - {'lee'}  ──▶  {'kim','park'}" },
  sorted_fn: { ana: "sort()의 복사본 버전 — 원본은 안 건드리고 정렬된 새 줄을 준다",
    io: "sorted({'c','a','b'})  ──▶  ['a','b','c']" },
  any_fn: { ana: "'한 명이라도 손 든 사람?' — 발견 즉시 그만 본다",
    io: "any('1' in row for row in g)  ──▶  True(남은 상자 있음)" },
  tuple_swap: { ana: "양손의 컵을 동시에 바꿔치기 — 임시 컵이 필요 없다",
    io: "a,b = 1,2 → a,b = b,a+b ──▶ a=2, b=3" },
  mod_arith: { ana: "주행거리계처럼 일정 값에서 되감기 — 숫자가 무한히 커지는 걸 방지",
    io: "(999999999 + 999999999) % 1000000007 = 999999991" },
  adj_list: { ana: "각자의 전화번호부: adj[나] = 내 친구 목록",
    io: "간선 1-2 ──▶ adj[1]=[2], adj[2]=[1]" },
  visited: { ana: "돌린 집 대문에 스티커 붙이기 — 두 번 안 돌게",
    io: "seen=[F,F,F] ──2번 방문──▶ [F,T,F]" },
  strip: { ana: "문자열 양끝의 보이지 않는 먼지(개행) 털기",
    io: "'101111\\n'  ──strip()──▶  '101111'" },
  print_fn: { ana: "마이크. 수만 번 말하는 것보다 원고를 모아 한 번에 읽는 게 빠르다",
    io: "print('\\n'.join(out))  ──▶  전체 결과 일괄 출력" },
  sql_select: { ana: "창고(FROM)에서 조건 맞는 상자만 골라(WHERE) 원하는 면만 보여주기(SELECT)",
    io: "products 6행 ──WHERE stock<10──▶ 4행 ──SELECT name,stock──▶ 2개 컬럼만" },
  sql_orderby: { ana: "결과를 내보내기 직전에 줄 세우기",
    io: "(pen,3)(ink,0)(tape,9) ──ORDER BY stock──▶ (ink,0)(pen,3)(tape,9)" },
  sql_join: { ana: "이름표(고객)와 영수증(주문)을 고객번호로 맞춰 옆에 붙이기",
    io: "kim(id1) + 주문(cust1, 300) ──JOIN──▶ (kim, 300) 한 행" },
  sql_groupby: { ana: "영수증을 고객별 봉투에 나눠 담고, 봉투마다 합계 스티커 붙이기",
    io: "kim:300, kim:200 ──GROUP BY+SUM──▶ kim: 500 (한 행)" },
  sql_having: { ana: "봉투를 만든 뒤에 봉투 자체를 거르는 체 (행 거르기는 WHERE)",
    io: "coffee(2개) bakery(3개) beverage(1개) ──HAVING COUNT>=2──▶ beverage 탈락" },
  sql_round_as: { ana: "반올림하고(ROUND), 결과 컬럼에 이름표 붙이기(AS)",
    io: "AVG=3533.33 ──ROUND──▶ 3533,  컬럼명 avg_price" },
  sql_subquery: { ana: "괄호 안에서 먼저 평균을 구해 쪽지에 적어두고, 본 쿼리가 그 쪽지와 비교",
    io: "(SELECT AVG(price))=40000 ──▶ WHERE price > 40000" },
  sql_rank: { ana: "부서별로 반을 나눠 등수 매기기 — 행은 그대로 두고 옆에 등수만 적는다",
    io: "data부서 6100,5200,5200,5000 ──RANK──▶ 1, 2, 2, 4 (DENSE_RANK면 1,2,2,3)" },
  sql_window_sum: { ana: "가계부: 줄마다 '여기까지 쓴 돈'을 옆 칸에 적기",
    io: "12000, 8000, 15000 ──SUM OVER──▶ 12000, 20000, 35000" },
};

/* ── 예제로 굴려보기: 예제 입력 기준 단계별 상태 변화 ── */
const TRACES = {
  1: { input: "예제: 4 2 / dana 90, alex 95, casey 90, blair 95", steps: [
    ["입력 파싱", "n=4, k=2"],
    ["튜플 저장", "[(-90,'dana'), (-95,'alex'), (-90,'casey'), (-95,'blair')]"],
    ["sort()", "[(-95,'alex'), (-95,'blair'), (-90,'casey'), (-90,'dana')] — -95(95점)가 맨 앞, 동점은 이름순"],
    ["rows[:2]", "(-95,'alex'), (-95,'blair')"],
    ["출력", "alex ↵ blair"],
  ]},
  2: { input: "예제: apple banana apple cherry banana", steps: [
    ["Counter", "{'apple': 2, 'banana': 2, 'cherry': 1}"],
    ["비교 키로 변환", "apple→(-2,'apple'), banana→(-2,'banana'), cherry→(-1,'cherry')"],
    ["min()", "(-2,'apple') — 개수 동점(–2)이라 이름 사전순으로 apple 승"],
    ["출력", "apple"],
  ]},
  3: { input: "예제: 4×6 미로 (출발 (1,1)=거리 1)", steps: [
    ["시작", "dist[0][0]=1, 큐=[(0,0)]"],
    ["(0,0) 꺼냄", "이웃 중 길은 아래 (1,0)뿐 → dist=2, 큐=[(1,0)]"],
    ["(1,0) 꺼냄", "(2,0) → dist=3 … 같은 방식으로 물결처럼 확산"],
    ["반복", "각 칸은 처음 도달할 때 한 번만 거리 기록 = 그게 최단"],
    ["종료", "dist[3][5]=15 → 출력 15"],
  ]},
  6: { input: "예제: 카드 5 6 7 8 9, M=21", steps: [
    ["(5,6,7)", "합 18 ≤ 21 → best=18"],
    ["(5,6,8)", "19 → best=19"],
    ["(5,6,9)", "20 → best=20"],
    ["(5,7,9)", "21 → best=21 (M과 정확히 일치)"],
    ["나머지 조합", "21 초과이거나 21 이하라도 21보다 작음 → 갱신 없음, 출력 21"],
  ]},
  7: { input: "예제: N=1260", steps: [
    ["500원", "1260//500=2개, 나머지 260"],
    ["100원", "260//100=2개, 나머지 60"],
    ["50원", "60//50=1개, 나머지 10"],
    ["10원", "10//10=1개, 나머지 0"],
    ["합계", "2+2+1+1 = 6개"],
  ]},
  8: { input: "예제: (1,4) (3,5) (0,6) (5,7) (8,9)", steps: [
    ["끝시간 정렬", "(1,4) (3,5) (0,6) (5,7) (8,9) — 이미 끝시간 순"],
    ["(1,4)", "1 ≥ -1 → 수락, end=4, cnt=1"],
    ["(3,5)", "3 < 4 → 겹침, 거절"],
    ["(0,6)", "0 < 4 → 거절"],
    ["(5,7)", "5 ≥ 4 → 수락, end=7, cnt=2"],
    ["(8,9)", "8 ≥ 7 → 수락, cnt=3 → 출력 3"],
  ]},
  9: { input: "예제: arr=[2,4,6,8,10], 질의 6, 3, 10", steps: [
    ["질의 6", "bisect_left→2, arr[2]==6 → '2'"],
    ["질의 3", "bisect_left→1, arr[1]=4≠3 → '-1'"],
    ["질의 10", "bisect_left→4, arr[4]==10 → '4'"],
    ["출력", "2 ↵ -1 ↵ 4"],
  ]},
  10: { input: "예제: 케이블 802 743 457 539, N=11", steps: [
    ["범위", "lo=1, hi=802"],
    ["mid=401", "802//401+743//401+457//401+539//401 = 2+1+1+1=5 < 11 → 불가, hi=400"],
    ["mid=200", "4+3+2+2 = 11 ≥ 11 → 가능! ans=200, lo=201"],
    ["mid=300", "2+2+1+1 = 6 < 11 → hi=299"],
    ["…반복", "가능/불가 경계를 좁혀도 200보다 큰 가능 값 없음 → 출력 200"],
  ]},
  11: { input: "예제: N=4", steps: [
    ["기저", "dp[1]=1 (1), dp[2]=2 (1+1, 2)"],
    ["dp[3]", "dp[2]+dp[1] = 3"],
    ["dp[4]", "dp[3]+dp[2] = 5 → 출력 5"],
    ["왜 더하기?", "4층에 오는 길은 '3층에서 1칸' 아니면 '2층에서 2칸' 둘뿐이라 두 경우의 수를 합친다"],
  ]},
  12: { input: "예제: -2 3 -1 4 -10 2", steps: [
    ["시작", "cur=-2, best=-2"],
    ["x=3", "max(3, -2+3=1) → cur=3, best=3 (앞의 -2를 버리고 새출발)"],
    ["x=-1", "max(-1, 3-1=2) → cur=2"],
    ["x=4", "max(4, 2+4=6) → cur=6, best=6 (구간 3,-1,4)"],
    ["x=-10", "max(-10, -4) → cur=-4"],
    ["x=2", "max(2, -2) → cur=2 — best는 여전히 6 → 출력 6"],
  ]},
  13: { input: "예제: 10 20 10 30 20 50", steps: [
    ["10", "tails=[10]"],
    ["20", "전부보다 큼 → 뒤에 추가, tails=[10,20]"],
    ["10", "같은 값 자리 교체 → tails=[10,20] (변화 없어 보이지만 '더 작은 끝값' 유지)"],
    ["30", "추가 → [10,20,30]"],
    ["20", "20 자리 교체 → [10,20,30]"],
    ["50", "추가 → [10,20,30,50] → 길이 4 출력"],
  ]},
  14: { input: "예제: 6명, 아는 사이 1-2, 2-3, 5-6", steps: [
    ["1번", "미방문 → 동아리① 발견, BFS로 {1,2,3} 전부 방문 처리"],
    ["2, 3번", "이미 방문 → 건너뜀"],
    ["4번", "미방문 → 동아리② (혼자)"],
    ["5번", "미방문 → 동아리③, BFS로 {5,6} 방문"],
    ["6번", "방문됨 → 끝. 출력 3"],
  ]},
  15: { input: "예제: 3×4, 감염원 (0,0)", steps: [
    ["0일", "큐에 감염원 전부 선적재 (여기선 1개)"],
    ["1일", "(0,0)의 이웃 정상 상자 (0,1), (1,0) 감염"],
    ["2일~", "물결처럼 확산, 벽(0)은 통과 못 함"],
    ["5일", "마지막 상자 (2,3) 감염 — days=5"],
    ["종료 검사", "'1' 남았나? 없음 → 출력 5 (남았으면 -1)"],
  ]},
  16: { input: "예제: 출근 kim lee park choi / 퇴근 lee kim", steps: [
    ["집합화", "arrived={kim,lee,park,choi}, left={lee,kim}"],
    ["차집합", "arrived - left = {park, choi}"],
    ["정렬·출력", "choi ↵ park (집합은 순서가 없어서 sorted 필수)"],
  ]},
  17: { input: "예제: but i wont but i", steps: [
    ["set", "{but, i, wont} — 중복 제거"],
    ["정렬 키", "i→(1,'i'), but→(3,'but'), wont→(4,'wont')"],
    ["출력", "i ↵ but ↵ wont (길이 우선, 같으면 사전순)"],
  ]},
  4: { input: "시드: kim 300+200, lee 150+350, park 700+0, choi 주문 없음", steps: [
    ["JOIN", "고객-주문 짝 맞춘 6행. choi는 짝이 없어 자동 탈락"],
    ["GROUP BY", "kim=500, lee=500, park=700 (고객당 한 행)"],
    ["ORDER BY", "park 700 → kim 500 → lee 500 (동액은 이름순)"],
  ]},
  5: { input: "시드: data 부서 6100, 5200, 5200, 5000", steps: [
    ["PARTITION", "부서별로 칸 나누기 (data / infra / ml)"],
    ["data 순위", "bae 6100→1등, ahn·cho 5200→공동 2등, ha 5000→4등 (3등 건너뜀 = RANK)"],
    ["비교", "DENSE_RANK였다면 ha는 3등 — 문제가 어느 쪽인지 확인"],
    ["출력 정렬", "부서 → 순위 → 이름 순으로 최종 정렬"],
  ]},
  18: { input: "시드: pen3 note25 clip3 tape9 glue10 ink0", steps: [
    ["WHERE stock<10", "note(25)·glue(10) 탈락 — 10은 '미만'이라 탈락인 게 포인트"],
    ["ORDER BY", "ink 0 → clip 3 → pen 3 (동률은 이름순) → tape 9"],
  ]},
  19: { input: "시드: coffee 2개, bakery 3개, beverage 1개, tea 2개", steps: [
    ["GROUP BY", "카테고리별 평균: coffee 4750, bakery 3533.33, beverage 6000, tea 4750"],
    ["HAVING", "beverage(1개) 탈락"],
    ["ROUND", "bakery 3533.33 → 3533"],
    ["ORDER BY", "coffee 4750 → tea 4750 (동점, 이름순) → bakery 3533"],
  ]},
  20: { input: "시드: 100000, 70000, 40000, 20000, 5000, 5000", steps: [
    ["서브쿼리", "AVG = 240000/6 = 40000"],
    ["WHERE >", "ssd 100000 ○, ram 70000 ○, fan 40000 ✕ (같은 건 '보다 비싼'이 아님)"],
    ["출력", "ssd → ram (가격 내림차순)"],
  ]},
  21: { input: "시드: 1일 12000, 3일 8000, 4일 15000, 7일 3000, 9일 21000, 10일 5000", steps: [
    ["1일", "누적 12000"],
    ["3일", "12000+8000 = 20000"],
    ["4일", "35000 … 행마다 '여기까지 합'이 붙는다"],
    ["10일", "64000 — 행 수는 그대로 6행 (GROUP BY와의 차이)"],
  ]},
};

/* ── 신규 8유형(22~29) 함수·문법 사전 ── */
Object.assign(FUNC_DICT, {
  stack_pat: {
    name: "스택 패턴 (append/pop)",
    sig: "st = [] / st.append(x) / st.pop()",
    what: "리스트를 '접시 쌓기'로 쓴다. 맨 위에 올리고(append) 맨 위에서 내린다(pop) — 마지막에 넣은 게 먼저 나온다(LIFO). 괄호 한 종류면 개수(depth)만 세도 같은 효과.",
    when: "괄호 짝, 되돌리기, '가장 최근 것부터 처리' 구조 전부.",
    ex: "st.append('('); st.pop()  # 짝 소거",
  },
  two_ptr_pat: {
    name: "투 포인터 (창 늘리고 줄이기)",
    sig: "for right in range(n): ... while 조건: left += 1",
    what: "구간의 양 끝을 가리키는 두 인덱스. right가 창을 넓히고, 조건이 차면 left가 창을 좁힌다. 둘 다 앞으로만 가서 전체 O(N).",
    when: "'조건 만족하는 연속 구간의 최소/최대' + 원소가 양수(단조성 있음)일 때.",
    ex: "cur += a[right]\nwhile cur >= s: cur -= a[left]; left += 1",
  },
  heapq_fn: {
    name: "heapq (최소 힙)",
    sig: "heapq.heapify(리스트) / heappop(h) / heappush(h, x)",
    what: "리스트를 '항상 최솟값이 맨 앞'인 구조로 유지한다. 꺼내기·넣기 모두 O(log N). 튜플을 넣으면 첫 원소 기준으로 정렬된다.",
    when: "'매번 가장 작은/큰 것'을 반복해서 꺼내는 문제. 다익스트라의 심장이기도 하다.",
    ex: "heapq.heapify(h)\na = heapq.heappop(h)  # 최솟값",
  },
  prefix_pat: {
    name: "누적합 배열 (prefix)",
    sig: "prefix[i+1] = prefix[i] + a[i]",
    what: "prefix[i] = 앞에서 i개의 합. 한 번 만들어두면(O(N)) 어떤 구간 합도 prefix[r] - prefix[l-1] 뺄셈 한 번(O(1)).",
    when: "구간 합을 여러 번 물을 때. N+1칸, prefix[0]=0으로 만들면 경계 예외가 없다.",
    ex: "a=[3,-1,4] → prefix=[0,3,2,6]\n(1,3)합 = prefix[3]-prefix[0] = 6",
  },
  dsu_pat: {
    name: "유니온 파인드 (find/union)",
    sig: "find(x): 뿌리 찾기 / parent[rb] = ra: 합치기",
    what: "덩어리마다 대표(뿌리)를 하나 둔다. find는 부모를 따라 뿌리까지 올라가면서 경로를 압축(부모→조부모)해 다음번을 빠르게 만든다. union은 두 뿌리를 잇는다.",
    when: "'같은 그룹인가?'를 수만 번 묻거나, 간선을 하나씩 추가하며 연결 상태를 관리할 때.",
    ex: "if find(x) == find(y): 같은 네트워크",
  },
  dijkstra_pat: {
    name: "다익스트라 패턴",
    sig: "pq = [(0, 시작)] → heappop → 낡으면 skip → 갱신하면 push",
    what: "힙에 (비용, 노드)를 넣고 비용이 싼 순서로 확정해 나간다. 꺼냈는데 기록(dist)보다 비싸면 낡은 항목이므로 버린다.",
    when: "가중치 있는 최단경로(음수 없음). 가중치가 전부 같으면 그냥 BFS가 더 싸다.",
    ex: "d, u = heappop(pq)\nif d > dist[u]: continue",
  },
  float_inf: {
    name: "float('inf') (무한대)",
    sig: "INF = float('inf')",
    what: "어떤 수보다도 큰 값. 최단거리의 '아직 도달 못 함' 초기값으로 쓴다. 어떤 비용과 비교해도 항상 진다.",
    when: "dist 배열 초기화, '없으면 -1' 판정(dist[n]이 그대로 INF면 미도달).",
    ex: "dist = [float('inf')] * (n+1)",
  },
  recursion_pat: {
    name: "재귀 DFS (고른다/안 고른다)",
    sig: "def dfs(i, 상태): ... dfs(i+1, A); dfs(i+1, B)",
    what: "i번째 원소에서 두 갈래(고름/안 고름)로 자기 자신을 다시 부른다. i==n에 도달하면 한 가지 조합이 완성된 것 — 거기서 조건 검사.",
    when: "모든 조합·순열을 빠짐없이 훑는 백트래킹. N이 20 안팎일 때만(2^N 폭발 주의).",
    ex: "dfs(i+1, acc + a[i], True)  # 고름\ndfs(i+1, acc, picked)       # 안 고름",
  },
  global_kw: {
    name: "global",
    sig: "def f(): global count; count += 1",
    what: "함수 안에서 바깥(전역) 변수를 수정하겠다는 선언. 없으면 파이썬이 새 지역 변수를 만들려다 에러를 낸다. 읽기만 할 때는 필요 없다.",
    when: "재귀 함수가 카운터를 올릴 때. (인자로 넘기고 반환값으로 모으는 방법도 있다)",
    ex: "count = 0\ndef dfs(...):\n    global count\n    count += 1",
  },
  run_scan: {
    name: "런 스캔 (같은 문자 뭉치 훑기)",
    sig: "while i < len(s): j=i; while s[j]==s[i]: j+=1; i=j",
    what: "i는 뭉치 시작, j는 같은 문자가 끝나는 지점까지 전진. 뭉치 길이 = j-i, 다음 뭉치는 i=j부터. 각 문자를 정확히 한 번씩만 본다 — O(N).",
    when: "연속 구간(런) 단위 처리: 압축, 그룹 개수 세기, 최장 연속 길이.",
    ex: "'aaab' → 런1: a×3 (i=0,j=3), 런2: b×1 (i=3,j=4)",
  },
});

Object.assign(FUNC_INTUIT, {
  stack_pat: { ana: "접시 쌓기 — 마지막에 올린 접시를 먼저 내린다",
    io: "append('(') append('(') pop() ──▶ 남은 깊이 1" },
  two_ptr_pat: { ana: "자벌레: 머리(right)가 늘어나고 꼬리(left)가 따라 붙는다",
    io: "[5,1,3,5,10,7...] S=15 → 창 [10,7](합17) ──줄이기──▶ 길이 2" },
  heapq_fn: { ana: "번호표 뽑는 창구인데 항상 '가장 작은 번호'부터 부른다",
    io: "[10,20,30,40] ──heappop×2──▶ 10, 20 (작은 둘)" },
  prefix_pat: { ana: "고속도로 누적 이정표: 구간 거리는 이정표 두 개 빼기",
    io: "a=[3,-1,4,1,5] → prefix=[0,3,2,6,7,12] → (2,5)합 = 12-3 = 9" },
  dsu_pat: { ana: "동아리마다 회장 한 명 — 같은 동아리인지는 회장이 같은지로 확인",
    io: "union(1,2), union(2,3) → find(3)=1 → find(1)==find(3) YES" },
  dijkstra_pat: { ana: "물이 낮은 곳부터 차오르듯, 비용이 싼 도시부터 차례로 확정",
    io: "힙 [(0,1)] → (2,2) (5,3) 후보 → 싼 (2,2) 먼저 확정" },
  float_inf: { ana: "아직 못 가본 곳의 거리표에 '무한대' 붙여두기",
    io: "dist=[inf,0,inf,...] → 갱신되면 숫자, 끝까지 inf면 -1 출력" },
  recursion_pat: { ana: "갈림길마다 분신을 둘로 나눠 양쪽 다 보내기",
    io: "원소 3개 → 2×2×2 = 8가지 조합을 전부 방문" },
  global_kw: { ana: "함수 안에서 '바깥 칠판에 쓰겠습니다' 손 들기",
    io: "global count 없이 count+=1 ──▶ UnboundLocalError" },
  run_scan: { ana: "같은 색 구슬 뭉치를 한 움큼씩 집어 세기",
    io: "'aaabbc' ──런 스캔──▶ (a,3) (b,2) (c,1) → 'a3b2c'" },
});

/* ── 신규 8문제 해설 ── */
Object.assign(GUIDE, {
  22: {
    concepts: [
      ["스택 = 최근 것부터", "괄호는 '가장 최근에 열린 것이 먼저 닫혀야' 하는 구조. 한 종류뿐이면 스택 대신 깊이 카운터 하나로 충분하다."],
      ["두 가지 실패 조건", "도중에 깊이가 음수(닫을 게 없는데 닫음), 끝났는데 0이 아님(덜 닫음). 둘 다 검사해야 한다."],
    ],
    blocks: [],
    funcs: ["stack_pat", "strip", "cond_expr", "print_fn"],
  },
  23: {
    concepts: [
      ["투 포인터의 전제: 단조성", "원소가 전부 양수라 창을 늘리면 합이 반드시 커진다. 이 단조성이 없으면(음수 섞임) 이 기법을 못 쓴다."],
      ["O(N)인 이유", "left와 right 모두 뒤로 돌아가지 않는다. 각각 최대 N번씩만 움직이므로 합쳐서 2N."],
    ],
    blocks: [],
    funcs: ["two_ptr_pat", "min_max_key", "map_int", "range_fn"],
  },
  24: {
    concepts: [
      ["왜 작은 것부터?", "먼저 합쳐진 파일은 이후 합칠 때마다 비용에 또 포함된다. 큰 파일을 일찍 합치면 그 큰 크기가 반복 청구되는 셈 — 작은 것부터가 최적."],
      ["힙이 필요한 이유", "'가장 작은 두 개'를 매번 정렬로 찾으면 너무 느리다. 힙은 꺼내기/넣기가 log N."],
    ],
    blocks: [],
    funcs: ["heapq_fn", "map_int", "print_fn"],
  },
  25: {
    concepts: [
      ["미리 계산해두기", "질의마다 다시 더하는 대신, '앞에서 i개까지의 합'을 한 번만 만들어두면 모든 질의가 뺄셈 한 번이 된다."],
      ["N+1칸의 이유", "prefix[0]=0을 깔아두면 l=1(맨 앞부터) 질의도 같은 식 prefix[r]-prefix[l-1]로 처리돼 예외가 사라진다."],
    ],
    blocks: [],
    funcs: ["prefix_pat", "buffer_read", "join", "list_fn"],
  },
  26: {
    concepts: [
      ["대표(뿌리)로 묶기", "'같은 덩어리인가'를 매번 탐색하지 않고, 덩어리마다 대표를 두고 대표만 비교한다."],
      ["경로 압축", "find로 올라가는 길에 부모를 조부모로 바꿔치기하면 트리가 납작해져서, 다음 find는 거의 한 걸음에 끝난다."],
    ],
    blocks: [],
    funcs: ["dsu_pat", "buffer_read", "join", "list_fn"],
  },
  27: {
    concepts: [
      ["BFS와의 차이", "간선 '개수' 최단이면 BFS, 간선 '비용 합' 최단이면 다익스트라. 큐가 힙으로 바뀐 BFS라고 생각하면 구조가 똑같이 읽힌다."],
      ["낡은 항목 스킵", "같은 도시가 힙에 여러 번 들어갈 수 있다. 꺼냈을 때 이미 더 싼 기록이 있으면 그건 과거의 낡은 후보 — 버린다. 이 두 줄이 다익스트라 오답/시간초과의 최다 원인."],
    ],
    blocks: [],
    funcs: ["dijkstra_pat", "heapq_fn", "float_inf", "adj_list", "cond_expr"],
  },
  28: {
    concepts: [
      ["2^N 완전탐색", "원소마다 고름/안 고름 → 조합 2^N개. N≤18이면 26만이라 전부 세도 된다. N이 크면 이 방법은 못 쓴다(그때는 DP·중간에서 만나기)."],
      ["빈 집합 함정", "T=0일 때 '아무것도 안 고른' 경우를 세면 안 된다. picked 플래그로 '1개 이상' 조건을 지킨다."],
    ],
    blocks: [],
    funcs: ["recursion_pat", "global_kw", "map_int", "print_fn"],
  },
  29: {
    concepts: [
      ["런(run) 단위로 생각", "글자 하나하나가 아니라 '같은 문자 뭉치'를 단위로 훑는다. i(시작)·j(끝) 두 인덱스 패턴은 문자열 구현 문제 전반에서 재사용된다."],
      ["문자열 이어붙이기 함정", "반복문에서 s += 조각 은 매번 새 문자열을 만들어 느리다. 리스트에 모아 마지막에 join이 정석."],
    ],
    blocks: [],
    funcs: ["run_scan", "join", "list_fn", "strip", "cond_expr"],
  },
});

Object.assign(TRACES, {
  22: { input: "예제: (())()", steps: [
    ["( ( ) )", "깊이 1 → 2 → 1 → 0 (음수 없음)"],
    ["( )", "깊이 1 → 0"],
    ["종료", "도중 음수 없음 + 최종 0 → YES"],
    ["반례 )( ", "첫 글자에서 깊이 -1 → 즉시 NO"],
  ]},
  23: { input: "예제: 5 1 3 5 10 7 4 9 2 8, S=15", steps: [
    ["right 확장", "[5,1,3,5,10] 합 24 ≥ 15 도달"],
    ["left 축소", "24→19→18→15(창 [3,5,10]·길이 3 기록)→10 (조건 깨짐, 축소 중단)"],
    ["right=5 (7)", "10+7=17 ≥ 15 → 축소: 12 (창 [10,7]·길이 2 기록!)"],
    ["이후", "길이 2보다 짧은 창은 안 나옴 → 답 2"],
  ]},
  24: { input: "예제: 10 20 30 40", steps: [
    ["1회", "작은 둘 10+20=30 합침 (비용 30) → 힙 [30,30,40]"],
    ["2회", "30+30=60 (비용 60, 누적 90) → [40,60]"],
    ["3회", "40+60=100 (비용 100, 누적 190) → [100]"],
    ["종료", "하나 남음 → 190"],
  ]},
  25: { input: "예제: 3 -1 4 1 5, 질의 (1,3)(2,5)(3,3)", steps: [
    ["prefix 생성", "[0, 3, 2, 6, 7, 12]"],
    ["(1,3)", "prefix[3]-prefix[0] = 6-0 = 6"],
    ["(2,5)", "prefix[5]-prefix[1] = 12-3 = 9"],
    ["(3,3)", "prefix[3]-prefix[2] = 6-2 = 4"],
  ]},
  26: { input: "예제: 케이블 1-2, 2-3, 4-5", steps: [
    ["union(1,2)", "2의 뿌리를 1로 → {1,2}"],
    ["union(2,3)", "find(2)=1, find(3)=3 → 3의 뿌리를 1로 → {1,2,3}"],
    ["union(4,5)", "{4,5}"],
    ["질의 1,3", "find(1)=1, find(3)=1 → YES"],
    ["질의 1,4", "1 vs 4 → NO / 질의 5,4 → 둘 다 4 → YES"],
  ]},
  27: { input: "예제: 5개 도시 6개 도로, 1→5", steps: [
    ["시작", "dist[1]=0, 힙 [(0,1)]"],
    ["1 확정", "이웃 갱신: 2번=2, 3번=5 → 힙 [(2,2),(5,3)]"],
    ["2 확정 (비용 2)", "3번을 2+1=3으로 갱신(5보다 쌈), 4번=9 → 힙 [(3,3),(5,3),(9,4)]"],
    ["3 확정 (비용 3)", "5번 = 3+6 = 9 / 낡은 (5,3)은 꺼낼 때 skip"],
    ["4 확정 (9)", "5번 = 9+3 = 12? 이미 9라 갱신 안 함 → dist[5]=9 출력"],
  ]},
  28: { input: "예제: -7 -3 -2 5 8, T=0", steps: [
    ["갈래 나누기", "원소마다 고름/안 고름 → 2^5 = 32가지 전부 방문"],
    ["예: {-3,-2,5}", "합 0, 1개 이상 → count+1"],
    ["예: 빈 집합", "합 0이지만 picked=False → 세지 않음 (함정 방어)"],
    ["종료", "count = 1"],
  ]},
  29: { input: "예제: aaabbc", steps: [
    ["런 1", "i=0, j→3: 'a'×3 → 'a3'"],
    ["런 2", "i=3, j→5: 'b'×2 → 'b2'"],
    ["런 3", "i=5, j→6: 'c'×1 → 'c' (1은 생략)"],
    ["비교", "'a3b2c'(5) < 'aaabbc'(6) → 압축본 출력"],
  ]},
});
